# Import Libraries

In [1]:
import pandas as pd
import numpy as np

# Import Datafile/ CSV file

In [2]:
ds=pd.read_csv(r'C:\Users\Kanneluri SanghavRao\Downloads\bank_churn_data (1).csv')

In [3]:
ds.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1  15634602.0  Hargrave          619    France  Female   42   
1          2  15647311.0      Hill          608     Spain  Female   41   
2          3  15619304.0      Onio          502    France  Female   42   
3          4  15701354.0      Boni          699    France  Female   39   
4          5  15737888.0  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0     2.0       0.00            1.0          1               1   
1     1.0   83807.86            1.0          0               1   
2     8.0  159660.80            3.0          1               0   
3     1.0       0.00            2.0          0               0   
4     2.0  125510.82            1.0          1               1   

   EstimatedSalary  Exited  
0        101348.88     1.0  
1        112542.58     0.0  
2        113931.57     1.0  
3         93826.63     0.0  
4         79084.10     0.0

In [4]:
ds.shape

(10000, 14)

In [5]:
ds.dtypes

RowNumber            int64
CustomerId         float64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure             float64
Balance            float64
NumOfProducts      float64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited             float64
dtype: object

In [6]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       9999 non-null   float64
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        9999 non-null   object 
 5   Gender           9998 non-null   object 
 6   Age              10000 non-null  int64  
 7   Tenure           9999 non-null   float64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    9998 non-null   float64
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  9999 non-null   float64
 13  Exited           9999 non-null   float64
dtypes: float64(6), int64(5), object(3)
memory usage: 1.1+ MB


In [7]:
ds.isnull().sum()

RowNumber          0
CustomerId         1
Surname            0
CreditScore        0
Geography          1
Gender             2
Age                0
Tenure             1
Balance            0
NumOfProducts      2
HasCrCard          0
IsActiveMember     0
EstimatedSalary    1
Exited             1
dtype: int64

In [8]:
ds.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

# Divide data into Identify Independent and Dependent 

In [9]:
#y=mx+c

In [10]:
x=ds[['RowNumber', 'CustomerId', 'Surname','Gender', 'Age','NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited' ]].values

In [11]:
x

array([[1, 15634602.0, 'Hargrave', ..., 1, 101348.88, 1.0],
       [2, 15647311.0, 'Hill', ..., 1, 112542.58, 0.0],
       [3, 15619304.0, 'Onio', ..., 0, 113931.57, 1.0],
       ...,
       [9998, 15584532.0, 'Liu', ..., 1, 42085.58, 1.0],
       [9999, 15682355.0, 'Sabbatini', ..., 0, 92888.52, 1.0],
       [10000, 15628319.0, 'Walker', ..., 0, 38190.78, 0.0]], dtype=object)

In [12]:
y=ds[['CreditScore','Tenure', 'Balance' ]].values

In [13]:
y

array([[6.1900000e+02, 2.0000000e+00, 0.0000000e+00],
       [6.0800000e+02, 1.0000000e+00, 8.3807860e+04],
       [5.0200000e+02, 8.0000000e+00, 1.5966080e+05],
       ...,
       [7.0900000e+02, 7.0000000e+00, 0.0000000e+00],
       [7.7200000e+02, 3.0000000e+00, 7.5075310e+04],
       [7.9200000e+02, 4.0000000e+00, 1.3014279e+05]])

In [14]:
#missing value treatment
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='median')

x[:,0:1]=imputer.fit_transform(x[:,0:1])

In [15]:
x

array([[1.0, 15634602.0, 'Hargrave', ..., 1, 101348.88, 1.0],
       [2.0, 15647311.0, 'Hill', ..., 1, 112542.58, 0.0],
       [3.0, 15619304.0, 'Onio', ..., 0, 113931.57, 1.0],
       ...,
       [9998.0, 15584532.0, 'Liu', ..., 1, 42085.58, 1.0],
       [9999.0, 15682355.0, 'Sabbatini', ..., 0, 92888.52, 1.0],
       [10000.0, 15628319.0, 'Walker', ..., 0, 38190.78, 0.0]],
      dtype=object)

In [16]:
x[:,1:2]=imputer.fit_transform(x[:,1:2])

In [17]:
y=imputer.fit_transform(y)
y[:,1:2]=imputer.fit_transform(y[:,1:2])

In [18]:
y

array([[6.1900000e+02, 2.0000000e+00, 0.0000000e+00],
       [6.0800000e+02, 1.0000000e+00, 8.3807860e+04],
       [5.0200000e+02, 8.0000000e+00, 1.5966080e+05],
       ...,
       [7.0900000e+02, 7.0000000e+00, 0.0000000e+00],
       [7.7200000e+02, 3.0000000e+00, 7.5075310e+04],
       [7.9200000e+02, 4.0000000e+00, 1.3014279e+05]])

# Apply Label Encoding 

In [19]:
from sklearn.preprocessing import LabelEncoder  
label=LabelEncoder()
x[:,5]=label.fit_transform(x[:,5])

In [20]:
x

array([[1.0, 15634602.0, 'Hargrave', ..., 1, 101348.88, 1.0],
       [2.0, 15647311.0, 'Hill', ..., 1, 112542.58, 0.0],
       [3.0, 15619304.0, 'Onio', ..., 0, 113931.57, 1.0],
       ...,
       [9998.0, 15584532.0, 'Liu', ..., 1, 42085.58, 1.0],
       [9999.0, 15682355.0, 'Sabbatini', ..., 0, 92888.52, 1.0],
       [10000.0, 15628319.0, 'Walker', ..., 0, 38190.78, 0.0]],
      dtype=object)

In [21]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
y[:,2]=label.fit_transform(y[:,2])


In [22]:
y

array([[6.190e+02, 2.000e+00, 0.000e+00],
       [6.080e+02, 1.000e+00, 7.430e+02],
       [5.020e+02, 8.000e+00, 5.793e+03],
       ...,
       [7.090e+02, 7.000e+00, 0.000e+00],
       [7.720e+02, 3.000e+00, 4.270e+02],
       [7.920e+02, 4.000e+00, 4.112e+03]])

In [23]:
ds.shape

(10000, 14)

# Split data into Train and Test

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [25]:
x_train.shape

(8000, 10)

In [26]:
y_train.shape

(8000, 3)

In [27]:
x_test.shape

(2000, 10)

In [28]:
y_test.shape

(2000, 3)